name: Runtime Risks

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy-and-monitor:
    runs-on: ubuntu-latest

    steps:
    - uses: cycodelabs/cimon-action@v0
      with:
          client-id: eu-a181449f-9daf-4cca-9a37-bb64f92dbc65
          secret: 8b36a9e9-5387-4453-9fd7-0a48a0addc8f
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install k3s
      run: |
        curl -sfL https://get.k3s.io | sh -
        sudo cp /etc/rancher/k3s/k3s.yaml $HOME/k3s.yaml
        sudo chown $USER $HOME/k3s.yaml
        echo "KUBECONFIG=$HOME/k3s.yaml" >> $GITHUB_ENV

    - name: Deploy test appliction
      run: |
        kubectl create deployment nginx --image=nginx
        POD=$(kubectl get pod -l app=nginx -o name)

    - name: Install Helm and kube-prometheus stack
      run: |
        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        chmod 700 get_helm.sh
        ./get_helm.sh
        helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
        helm repo update
        helm install kps prometheus-community/kube-prometheus-stack
